// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "f5163e81-65b1-4305-965c-a1c83371c52d");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1595699229);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1595699228);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1085);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1595699218);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6c0fce61-a7e6-48f9-b206-fa108a4f7398}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.slowStartup.averageTime", 8207);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200708170202");
user_pref("browser.startup.homepage_override.mstone", "78.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1595699220);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1595699226889");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.0.2");
user_pref("extensions.lastPlatformVersion", "78.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"eafca62f-79fa-4d77-a660-2f6edef8f77b\",\"formautofill@mozilla.org\":\"1c4adf28-bd4d-483f-92a3-2bbfcbc524a6\",\"screenshots@mozilla.org\":\"82f4c9db-db32-44d4-8fa5-195420c13922\",\"webcompat-reporter@mozilla.org\":\"4f4b87dc-3667-4b0c-8053-4572af96a4ea\",\"webcompat@mozilla.org\":\"bfba1cb4-aca5-4e8e-bcac-25508d5732b5\",\"default-theme@mozilla.org\":\"790db069-da72-4841-8f8f-5961f1089bdb\",\"google@search.mozilla.org\":\"125163d7-16bc-40a3-918d-392b7ac87693\",\"amazondotcom@search.mozilla.org\":\"0eaf7a74-8762-42db-b23e-bf5f284aef6d\",\"bing@search.mozilla.org\":\"1dc94646-dbfc-4c81-b7ea-961aaa3507fb\",\"ddg@search.mozilla.org\":\"64d069c9-ced1-4e78-b472-da6650bdc201\",\"ebay@search.mozilla.org\":\"7b818713-1303-4c1d-a594-43f9659a2dc8\",\"wikipedia@search.mozilla.org\":\"283b44fb-7829-4fb6-8800-08d284ca40ea\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "ca3438a9-e280-47de-b411-91c6f50ab249");
user_pref("security.sandbox.plugin.tempDirSuffix", "198c5f14-d3e4-4afd-8882-fa2f0e823701");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1595699211);
user_pref("toolkit.telemetry.cachedClientID", "b9d0fd59-6b23-47cb-b88c-02b646988a6f");
user_pref("toolkit.telemetry.previousBuildID", "20200708170202");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
